import { PermissionFlagsBits } from 'discord.js';
import type { RoleConfig } from '../types/server-config.types.js';
import { BRANDING } from './branding.config.js';

export const ROLE_NAMES = {
  founder: '神 (Fondateur)',
  admin: '🛡️・Admin',
  moderator: '🔧・Modérateur',
  elder: '⭐・Ancien',
  member: '✅・Membre',
  pending: '🕯️・À valider',
  guest: '👁️・Invité',
  bot: '🤖・Bot',
  botModeration: '🛠️・Bot Modération',
  botTickets: '🎫・Bot Tickets',
  botVoice: '🔊・Bot Vocal',
  botEvents: '📅・Bot Events',
  botStats: '📊・Bot Stats',
  botNews: '📰・Bot News',
  botStarboard: '⭐・Bot Starboard',
  botMusic: '🎵・Bot Music',
  muted: '🔇・Muted',
} as const;

export const PROTECTED_ROLE_NAMES = [
  ROLE_NAMES.founder,
  ROLE_NAMES.admin,
  ROLE_NAMES.moderator,
  ROLE_NAMES.member,
] as const;

export const SERVER_ROLES: RoleConfig[] = [
  {
    name: ROLE_NAMES.founder,
    color: BRANDING.colors.founderGold,
    hoist: true,
    mentionable: false,
    permissions: [],
    kind: 'hierarchy',
    protected: true,
  },
  {
    name: ROLE_NAMES.admin,
    color: '#E74C3C',
    hoist: true,
    mentionable: false,
    permissions: [
      PermissionFlagsBits.ManageChannels,
      PermissionFlagsBits.ManageRoles,
      PermissionFlagsBits.ManageMessages,
      PermissionFlagsBits.ViewAuditLog,
    ],
    kind: 'hierarchy',
  },
  {
    name: ROLE_NAMES.moderator,
    color: '#3498DB',
    hoist: true,
    mentionable: false,
    permissions: [
      PermissionFlagsBits.ManageMessages,
      PermissionFlagsBits.ModerateMembers,
      PermissionFlagsBits.ViewAuditLog,
    ],
    kind: 'hierarchy',
  },
  {
    name: ROLE_NAMES.elder,
    color: BRANDING.colors.lavender,
    hoist: true,
    mentionable: false,
    permissions: [],
    kind: 'hierarchy',
  },
  {
    name: ROLE_NAMES.member,
    color: '#2ECC71',
    hoist: false,
    mentionable: false,
    permissions: [],
    kind: 'hierarchy',
  },
  {
    name: ROLE_NAMES.pending,
    color: BRANDING.colors.coldGrey,
    hoist: false,
    mentionable: false,
    permissions: [],
    kind: 'hierarchy',
  },
  {
    name: ROLE_NAMES.guest,
    color: '#7F8C8D',
    hoist: false,
    mentionable: false,
    permissions: [],
    kind: 'hierarchy',
  },
  {
    name: ROLE_NAMES.bot,
    color: '#5865F2',
    hoist: true,
    mentionable: false,
    permissions: [],
    kind: 'hierarchy',
  },
  {
    name: ROLE_NAMES.botModeration,
    color: '#3498DB',
    hoist: true,
    mentionable: false,
    permissions: [PermissionFlagsBits.ManageRoles, PermissionFlagsBits.ManageMessages],
    kind: 'hierarchy',
  },
  {
    name: ROLE_NAMES.botTickets,
    color: '#9B59B6',
    hoist: true,
    mentionable: false,
    permissions: [PermissionFlagsBits.ManageChannels, PermissionFlagsBits.ManageMessages],
    kind: 'hierarchy',
  },
  {
    name: ROLE_NAMES.botVoice,
    color: '#1ABC9C',
    hoist: true,
    mentionable: false,
    permissions: [PermissionFlagsBits.ManageChannels, PermissionFlagsBits.MoveMembers],
    kind: 'hierarchy',
  },
  {
    name: ROLE_NAMES.botEvents,
    color: '#E67E22',
    hoist: true,
    mentionable: false,
    permissions: [],
    kind: 'hierarchy',
  },
  {
    name: ROLE_NAMES.botStats,
    color: '#95A5A6',
    hoist: true,
    mentionable: false,
    permissions: [],
    kind: 'hierarchy',
  },
  {
    name: ROLE_NAMES.botNews,
    color: '#F1C40F',
    hoist: true,
    mentionable: false,
    permissions: [],
    kind: 'hierarchy',
  },
  {
    name: ROLE_NAMES.botStarboard,
    color: '#F39C12',
    hoist: true,
    mentionable: false,
    permissions: [],
    kind: 'hierarchy',
  },
  {
    name: ROLE_NAMES.botMusic,
    color: '#2ECC71',
    hoist: true,
    mentionable: false,
    permissions: [],
    kind: 'hierarchy',
  },
  {
    name: ROLE_NAMES.muted,
    color: '#555555',
    hoist: false,
    mentionable: false,
    permissions: [],
    kind: 'hierarchy',
  },
  {
    name: '🎯・Valorant',
    color: BRANDING.colors.lavender,
    hoist: false,
    mentionable: false,
    permissions: [],
    kind: 'interest',
  },
  {
    name: '⛏️・Minecraft',
    color: BRANDING.colors.lavender,
    hoist: false,
    mentionable: false,
    permissions: [],
    kind: 'interest',
  },
  {
    name: '🎮・Gaming',
    color: BRANDING.colors.lavender,
    hoist: false,
    mentionable: false,
    permissions: [],
    kind: 'interest',
  },
  {
    name: '🍜・Anime',
    color: BRANDING.colors.lavender,
    hoist: false,
    mentionable: false,
    permissions: [],
    kind: 'interest',
  },
  {
    name: '🎬・Films & Séries',
    color: BRANDING.colors.lavender,
    hoist: false,
    mentionable: false,
    permissions: [],
    kind: 'interest',
  },
  {
    name: '🎧・Musique',
    color: BRANDING.colors.lavender,
    hoist: false,
    mentionable: false,
    permissions: [],
    kind: 'interest',
  },
  {
    name: '🎨・Créatif',
    color: BRANDING.colors.lavender,
    hoist: false,
    mentionable: false,
    permissions: [],
    kind: 'interest',
  },
  {
    name: '📺・Stream',
    color: BRANDING.colors.lavender,
    hoist: false,
    mentionable: false,
    permissions: [],
    kind: 'interest',
  },
  {
    name: '💻・Dev',
    color: BRANDING.colors.lavender,
    hoist: false,
    mentionable: false,
    permissions: [],
    kind: 'interest',
  },
  {
    name: '📢・Annonces',
    color: BRANDING.colors.founderGold,
    hoist: false,
    mentionable: false,
    permissions: [],
    kind: 'notification',
  },
  {
    name: '🎮・Game Night',
    color: BRANDING.colors.founderGold,
    hoist: false,
    mentionable: false,
    permissions: [],
    kind: 'notification',
  },
  {
    name: '🎬・Watch Party',
    color: BRANDING.colors.founderGold,
    hoist: false,
    mentionable: false,
    permissions: [],
    kind: 'notification',
  },
  {
    name: '🎁・Free Games',
    color: BRANDING.colors.founderGold,
    hoist: false,
    mentionable: false,
    permissions: [],
    kind: 'notification',
  },
  {
    name: '📊・Sondages',
    color: BRANDING.colors.founderGold,
    hoist: false,
    mentionable: false,
    permissions: [],
    kind: 'notification',
  },
  {
    name: '📰・Patch Notes',
    color: BRANDING.colors.founderGold,
    hoist: false,
    mentionable: false,
    permissions: [],
    kind: 'notification',
  },
  {
    name: '🌑・Bleu Nuit',
    color: BRANDING.colors.midnightBlue,
    hoist: false,
    mentionable: false,
    permissions: [],
    kind: 'color',
  },
  {
    name: '💜・Lavande',
    color: BRANDING.colors.lavender,
    hoist: false,
    mentionable: false,
    permissions: [],
    kind: 'color',
  },
  {
    name: '🤍・Blanc',
    color: '#FFFFFF',
    hoist: false,
    mentionable: false,
    permissions: [],
    kind: 'color',
  },
  {
    name: '🖤・Noir',
    color: '#111111',
    hoist: false,
    mentionable: false,
    permissions: [],
    kind: 'color',
  },
  {
    name: '🌸・Rose',
    color: '#FF8FB3',
    hoist: false,
    mentionable: false,
    permissions: [],
    kind: 'color',
  },
  {
    name: '💎・Cyan',
    color: '#00D1FF',
    hoist: false,
    mentionable: false,
    permissions: [],
    kind: 'color',
  },
  {
    name: '🍃・Menthe',
    color: '#7DFFB3',
    hoist: false,
    mentionable: false,
    permissions: [],
    kind: 'color',
  },
  {
    name: '🔥・Rouge',
    color: '#E74C3C',
    hoist: false,
    mentionable: false,
    permissions: [],
    kind: 'color',
  },
  {
    name: '☀️・Or',
    color: BRANDING.colors.founderGold,
    hoist: false,
    mentionable: false,
    permissions: [],
    kind: 'color',
  },
];

export const INTEREST_ROLE_NAMES = SERVER_ROLES.filter((role) => role.kind === 'interest').map(
  (role) => role.name,
);
export const NOTIFICATION_ROLE_NAMES = SERVER_ROLES.filter(
  (role) => role.kind === 'notification',
).map((role) => role.name);
export const COLOR_ROLE_NAMES = SERVER_ROLES.filter((role) => role.kind === 'color').map(
  (role) => role.name,
);
